products:
  wofs_albers:
    prefix: WOfS/WOFLs/v2.1.5/combined
    name_template: x_{x}/y_{y}/{time:%Y}/{time:%m}/{time:%d}/LS_WATER_3577_{x}_{y}_{time:%Y%m%d%H%M%S%f}
    stacked_name_template: x_{x}/y_{y}/{time:%Y}/{time:%m}/{time:%d}/LS_WATER_3577_{x}_{y}_{time:%Y}_
    predictor: 2
    nonpym_list: ["source", "observed"]
    default_rsp: average

  wofs_filtered_summary:
    prefix: WOfS/filtered_summary/v2.1.0/combined
    name_template: x_{x}/y_{y}/wofs_filtered_summary_{x}_{y}
    stacked_name_template: x_{x}/y_{y}/wofs_filtered_summary_{x}_{y}
    predictor: 2
    nonpym_list: ["source", "observed"]
    default_rsp: average

  wofs_summary:
    prefix: WOfS/summary/v2.1.0/combined
    name_template: x_{x}/y_{y}/WOFS_3577_{x}_{y}_summary
    stacked_name_template: x_{x}/y_{y}/WOFS_3577_{x}_{y}_summary
    predictor: 2
    nonpym_list: ["source", "observed"]
    default_rsp: average

  wofs_annual_summary:
    prefix: WOfS/annual_summary/v2.1.5/combined
    name_template: x_{x}/y_{y}/{time:%Y}/WOFS_3577_{x}_{y}_{time:%Y}_summary
    stacked_name_template: x_{x}/y_{y}/{time:%Y}/WOFS_3577_{x}_{y}_{time:%Y}_summary
    predictor: 2
    nonpym_list: ["source", "observed"]
    default_rsp: average

  ls5_fc_albers:
    prefix: fractional-cover/fc/v2.2.0/ls5
    name_template: x_{x}/y_{y}/{time:%Y}/{time:%m}/{time:%d}/LS5_TM_FC_3577_{x}_{y}_{time:%Y%m%d%H%M%S%f}
    stacked_name_template: x_{x}/y_{y}/{time:%Y}/{time:%m}/{time:%d}/LS5_TM_FC_3577_{x}_{y}_{time:%Y}_
    predictor: 2
    nonpym_list: ["source", "observed"]
    default_rsp: average

  ls7_fc_albers:
    prefix: fractional-cover/fc/v2.2.0/ls7
    name_template: x_{x}/y_{y}/{time:%Y}/{time:%m}/{time:%d}/LS7_ETM_FC_3577_{x}_{y}_{time:%Y%m%d%H%M%S%f}
    stacked_name_template: x_{x}/y_{y}/{time:%Y}/{time:%m}/{time:%d}/LS7_ETM_FC_3577_{x}_{y}_{time:%Y}_
    predictor: 2
    nonpym_list: ["source", "observed"]
    default_rsp: average

  ls8_fc_albers:
    prefix: fractional-cover/fc/v2.2.0/ls8
    name_template: x_{x}/y_{y}/{time:%Y}/{time:%m}/{time:%d}/LS8_OLI_FC_3577_{x}_{y}_{time:%Y%m%d%H%M%S%f}
    stacked_name_template: x_{x}/y_{y}/{time:%Y}/{time:%m}/{time:%d}/LS8_OLI_FC_3577_{x}_{y}_{time:%Y}_
    predictor: 2
    nonpym_list: ["source", "observed"]
    default_rsp: average

  fc_percentile_albers_annual:
    prefix: fractional-cover/fc-percentile/annual/v2.1.0/combined
    name_template: x_{x}/y_{y}/{time:%Y}/LS_FC_PC_3577_{x}_{y}_{time:%Y%m%d}
    stacked_name_template: x_{x}/y_{y}/{time:%Y}/LS_FC_PC_3577_{x}_{y}_{time:%Y%m%d}
    predictor: 2
    nonpym_list: ["source", "observed"]
    default_rsp: average

  fc_percentile_seasonal:  # fc_percentile_seasonal product is not found in ODC datacube
    prefix: fractional-cover/fc-percentile/seasonal/v2.1.0/combined
    name_template: x_{x}/y_{y}/LS_FC_PC_3577_{x}_{y}_{start_time:%Y%m%d}_{end_time:%Y%m%d}
    stacked_name_template: x_{x}/y_{y}/LS_FC_PC_3577_{x}_{y}_{start_time:%Y%m%d}_{end_time:%Y%m%d}
    predictor: 2
    nonpym_list: ["source", "observed"]
    default_rsp: average

  ls8_barest_earth_mosaic:
    prefix: bare-earth/summary/v2.1.1/L8
    name_template: x_{x}/y_{y}/be-l8_{x}_{y}
    stacked_name_template: x_{x}/y_{y}/be-l8_{x}_{y}
    predictor: 2
    nonpym_list: ["source", "observed"]
    default_rsp: average

  ls5_nbart_geomedian_annual:
    prefix: geomedian-australia/v2.1.0/L5
    name_template: x_{x}/y_{y}/{time:%Y/%m/%d}/ls5_gm_nbart_{x}_{y}_{time:%Y%m%d}
    stacked_name_template: x_{x}/y_{y}/{time:%Y/%m/%d}/ls5_gm_nbart_{x}_{y}_{time:%Y%m%d}
    predictor: 2
    nonpym_list: ["source", "observed"]
    default_rsp: average

  ls7_nbart_geomedian_annual:
    prefix: geomedian-australia/v2.1.0/L7
    name_template: x_{x}/y_{y}/{time:%Y/%m/%d}/ls7_gm_nbart_{x}_{y}_{time:%Y%m%d}
    stacked_name_template: x_{x}/y_{y}/{time:%Y/%m/%d}/ls7_gm_nbart_{x}_{y}_{time:%Y%m%d}
    predictor: 2
    nonpym_list: ["source", "observed"]
    default_rsp: average

  ls8_nbart_geomedian_annual:
    prefix: geomedian-australia/v2.1.0/L8
    name_template: x_{x}/y_{y}/{time:%Y/%m/%d}/ls8_gm_nbart_{x}_{y}_{time:%Y%m%d}
    stacked_name_template: x_{x}/y_{y}/{time:%Y/%m/%d}/ls8_gm_nbart_{x}_{y}_{time:%Y%m%d}
    predictor: 2
    nonpym_list: ["source", "observed"]
    default_rsp: average

  item_v2:
    prefix: item_v2/v2.0.1/relative
    name_template: lon_{lon}/lat_{lat}/ITEM_REL_{lon}_{lat}
    stacked_name_template: lon_{lon}/lat_{lat}/ITEM_REL_{lon}_{lat}
    predictor: 2
    nonpym_list: ["source", "observed"]
    default_rsp: average

  item_v2_conf:
    prefix: item_v2/v2.0.1/confidence
    name_template: lon_{lon}/lat_{lat}/ITEM_STD_{lon}_{lat}
    stacked_name_template: lon_{lon}/lat_{lat}/ITEM_STD_{lon}_{lat}
    predictor: 2
    nonpym_list: ["source", "observed"]
    default_rsp: average

  multi-scale-topographic-position:
    prefix: multi-scale-topographic-position/v1.0.1
    name_template: lon_{lon}/lat_{lat}/MSTP_{lon}_{lat}
    stacked_name_template: lon_{lon}/lat_{lat}/MSTP_{lon}_{lat}
    predictor: 2
    nonpym_list: ["source", "observed"]
    default_rsp: average

  nidem:
    prefix: nidem/v1.0.0
    name_template: lon_{lon}/lat_{lat}/NIDEM_{lon}_{lat}
    stacked_name_template: lon_{lon}/lat_{lat}/NIDEM_{lon}_{lat}
    predictor: 2
    nonpym_list: ["source", "observed"]
    default_rsp: average

  weathering-intensity:
    prefix: weathering-intensity/v1.0.1
    name_template: lon_{lon}/lat_{lat}/WEATHER_INTENSITY_{lon}_{lat}
    stacked_name_template: lon_{lon}/lat_{lat}/WEATHER_INTENSITY_{lon}_{lat}
    predictor: 2
    nonpym_list: ["source", "observed"]
    default_rsp: average

  mangrove_cover:
    prefix: mangrove_cover
    name_template: "{x}_{y}/MANGROVE_COVER_3577_{x}_{y}_{time:%Y%m%d}"
    stacked_name_template: "{x}_{y}/MANGROVE_COVER_3577_{x}_{y}_{time:%Y%m%d}"
    predictor: 2
    nonpym_list: ["source", "observed"]
    default_rsp: average
